#!/bin/bash -e

echo "Building..."

if [[ $# == 0 || $1 == "schema" ]]; then
  echo "Generating schema..."
  mkdir -p build/schema
  env -C src grep -rn "@schema" \
    | sed -e "s%\(.*\)\.ts.*@schema \(.*\)%\2%" \
    | xargs node .side/scripts/schema-gen.js
fi

if [[ $# == 0 || $1 == "status" ]]; then
  echo "Compiling status..."
  g++ src/status.cpp -static -Os -s -o build/__status -lstdc++fs
fi

if [[ $# == 0 || $1 == "side" ]]; then
  echo "Compiling side..."
  ncc build src/side.ts -q -m --v8-cache --no-source-map-register -o build/
  mv build/index.js build/side.js
  sed -i -e '1s|^|#!/usr/bin/env node\n|' build/side.js
  chmod +x build/side.js
  ln -rfs build/side.js build/side
fi

if [[ $# == 0 || $1 == "server" ]]; then
echo "Compiling dist-server..."
ncc build src/dist-server.ts -q --v8-cache --no-source-map-register -o build/
mv build/index.js build/dist-server.js
sed -i -e '1s|^|#!/usr/bin/env node\n|' build/dist-server.js
fi

echo "Writing build info..."
build/side vset \
  -f json \
  -o build/package.json \
  build/package.json \
  version=\"$(build/side vget package.json version)\"

build/side vset \
  -f json \
  -o build/package.json \
  build/package.json \
  revision=\"$(build/side vget build/build-info.json revision)\"