#!/bin/bash -e

ncc build src/index.ts -m --v8-cache --no-source-map-register -o build

if which side; then
    version=$(side vget package.json version)
    side vset -o build/package.json -f json build/package.json version=\"${version}\"
fi