#!/bin/bash

rm -rf ${SIDE_DIR_PACKAGE}
mkdir -p ${SIDE_DIR_PACKAGE}
cp -r ${SIDE_DIR_BUILD} ${SIDE_DIR_PACKAGE}/side

mkdir -p ${SIDE_DIR_RELEASE}
env -C ${SIDE_DIR_PACKAGE} tar -Jcf ${SIDE_PROJECT}/${SIDE_DIR_RELEASE}/side.tar.xz side
rm -rf ${SIDE_DIR_PACKAGE}